# Generated by Django 4.1 on 2022-08-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('birthday', models.DateField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
